### ISSUE TITLE
Falha na dependência node-beep

### ISSUE THREAD

**Issue by adelitofarias** [forex-social/crypto-arbitrage-br#3]
Saudações!

Ao tentar executar, acusa um erro no node-beep e não consigo instalar na minha máquina.
Node: 7.10.0
NPM: 5.5.1 

Como proceder?

![captura de tela de 2017-11-29 15-49-27](https://user-images.githubusercontent.com/19351435/33393189-1cc8c04c-d51d-11e7-868d-89a1501d23f2.png)

**Comment by vicenterusso** [comment]
+1

**Comment by brubrant** [comment]
Obrigado @adelitofarias e @vicenterusso corrigi hoje.
